name: IOS

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@main
      - name: Build
      # run: xcodebuild
        run: swift build -v
      # - name: Run tests
      #   run: swift test -v